---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: default
  labels:
    app: auth-deployment
spec:
  selector:
    matchLabels:
      app: auth-deployment
  template:
    metadata:
      labels:
        app: auth-deployment
    spec:
      containers:
        - name: auth-service
          image: backendprogramminglearningsystemrepository.azurecr.io/auth.service:1.0-SNAPSHOT
#          image: com.backend.programming.learning.system/auth.service:1.0-SNAPSHOT
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://aws-postgresql.ctso2e4midpm.ap-southeast-2.rds.amazonaws.com:5432/auth-service?currentSchema=public&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgresadmin"
            - name: SPRING_DATASOURCE_INITIALIZATION-MODE
              value: "never"
            - name: KAFKA-CONFIG_BOOTSTRAP-SERVERS
              value: "gke-confluent-kafka-cp-kafka-headless:9092"
            - name: KAFKA-CONFIG_SCHEMA-REGISTRY-URL
              value: "http://gke-confluent-kafka-cp-schema-registry:8081"
          resources:
            limits:
              cpu: "300m"
              memory: "1024Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: default
  labels:
    app: auth-service
spec:
  selector:
    app: auth-deployment
  ports:
    - name: auth-service-port
      protocol: TCP
      port: 8182
  type: LoadBalancer
  loadBalancerIP: ""
---
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: auth-deployment-hpa
#  namespace: default
#  labels:
#    app: auth-deployment
#spec:
#  scaleTargetRef:
#    kind: Deployment
#    name: auth-deployment
#    apiVersion: apps/v1
#  minReplicas: 2
#  maxReplicas: 4
#  metrics:
#    - type: Resource
#      resource:
#        name: cpu
#        target:
#          type: Utilization
#          averageUtilization: 85
