global:
  configMapName: backend-programming-learning-system-dev-configmap
  activeProfile: default
  configServerURL: "http://config-server:9999"
  discoveryServerURL: "http://discovery-service:8761/eureka"
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/app/libs/opentelemetry-javaagent-1.32.0.jar"
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4317
  otelMetricsExporter: none
  kafkaBootstrapServers: local-confluent-kafka-cp-kafka-headless:9092
  kafkaSchemaRegistryURL: http://local-confluent-kafka-cp-schema-registry:8081
  springDatasourceHost: host.docker.internal
  springDatasourcePort: 5432
  springDatasourceUsername: postgres
  springDatasourcePassword: localdb
  springDatasourceInitializationMode: always
  springDataRedisHost: redis-master
  springDataRedisPort: 6379
  springDataRedisPassword: admin
  loggingLevelRoot: DEBUG
  loggingLevelComBackendProgrammingLearningSystem: DEBUG