---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  namespace: default
  labels:
    app: gateway-service
spec:
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      containers:
        - name: gateway-service
          image: com.backend.programming.learning.system/gateway.service:1.0-SNAPSHOT
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Xmx256m -Xms128m"
            - name: LOGGING_LEVEL_ROOT
              value: "debug"
            - name: LOGGING_LEVEL_COM_BACKEND_PROGRAMMING_LEARNING_SYSTEM
              value: "debug"
            - name: SERVER_PORT
              value: "9098"
            - name: CONFIG_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: CONFIG_SERVER
            - name: SPRING_REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_REDIS_HOST
            - name: SPRING_REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_REDIS_PORT
            - name: SPRING_REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_REDIS_PASSWORD
            - name: EUREKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: EUREKA_SERVER
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              valueFrom:
                configMapKeyRef:
                  name: backend-programming-learning-system-configmap
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "200m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: default
  labels:
    app: gateway-service
spec:
  selector:
    app: gateway-service
  ports:
    - name: gateway-service-port
      protocol: TCP
      port: 9098
  type: LoadBalancer
  loadBalancerIP: ""